
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SFS.ServiceDesk.BusinessObjects
{

using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using SFSdotNet.Framework.Common.Entities;
    
[JsonObject(IsReference = true)]
[DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
public partial class SDProxyUser : ITrackable
{

    public SDProxyUser()
    {
	
		this.ModifiedProperties = new List<string>();

        this.SDPersons = new List<SDPerson>();

    }


    [DataMember]
        public System.Guid GuidUser { get; set; }

    [DataMember]
        public string Email { get; set; }

    [DataMember]
        public string DisplayName { get; set; }



    [DataMember]
        public ICollection<SDPerson> SDPersons { get; set; }


    [DataMember]
    public TrackingState TrackingState { get; set; }
    [DataMember]
    public ICollection<string> ModifiedProperties { get; set; }
    [JsonProperty, DataMember]
    private Guid EntityIdentifier { get; set; }
}

}
