//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFS.ServiceDesk.Web.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFS.ServiceDesk.Web.Mvc.Resources.ModuleResources", typeof(ModuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs.
        /// </summary>
        public static string CATALOGS {
            get {
                return ResourceManager.GetString("CATALOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FILES {
            get {
                return ResourceManager.GetString("FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFSServiceDesk.
        /// </summary>
        public static string MODULE_NAME {
            get {
                return ResourceManager.GetString("MODULE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciones.
        /// </summary>
        public static string OPERATIONS {
            get {
                return ResourceManager.GetString("OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This a &lt;b&gt;short&lt;/b&gt; description for place in all application list.
        /// </summary>
        public static string SHORT_DESCRIPTION {
            get {
                return ResourceManager.GetString("SHORT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario ya existe, escoge otro.
        /// </summary>
        public static string USERNAME_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USERNAME_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios y roles.
        /// </summary>
        public static string USERS_AND_ROLES {
            get {
                return ResourceManager.GetString("USERS_AND_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work flows.
        /// </summary>
        public static string WORKFLOWS {
            get {
                return ResourceManager.GetString("WORKFLOWS", resourceCulture);
            }
        }
    }
}
